services:
  auth_web:
    build:
      context: ./django
      args:
        - VOLUME=${DJANGO_WORKDIR:-/home/Auth}
        - LAUNCH=${DJANGO_LAUNCH_REPO:-/run/launch}
    container_name: django-Auth
    command: python manage.py runserver 0.0.0.0:8000 
    ports:
      - "8001:8000"
    volumes:
      - ../djpr_Registery:${DJANGO_WORKDIR:-/home/Auth}
    environment:
      - POSTGRES_USER=${PSQL_USER:-default_us}
      - POSTGRES_PASSWORD=${PSQL_PASS:-default_ps}
      - POSTGRES_DB=${SQL_DATABASE:-default_db}
    env_file:
      - .env
    depends_on:
      auth_psql:
        condition: "service_healthy"
    networks:
      - backend
      - auth_db
    restart: always

  auth_psql:
    container_name: postgreSQL-Auth
    build:
      context: ./postgresql
      args:
        - POSTGRES_USER=${PSQL_USER:-default_us}
        - POSTGRES_PASSWORD=${PSQL_PASS:-default_ps}
        - POSTGRES_DB=${SQL_DATABASE:-default_db}
    volumes:
      - /home/eslamber/data/Auth:${PSQL_DATA_REPO}
      - ./postgresql/tools:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - "5431:5432"
    networks:
      - auth_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $USER"]
      start_period: 5s
      retries: 10
      interval: 15s
      timeout: 10s
    restart: on-failure

networks:
  backend:
    name: backend
    driver: bridge

  auth_db:
    name: auth_db
    driver: bridge
